### ISSUE TITLE
IntelliJ + New UI: actions not directly visible

### ISSUE THREAD

**Issue by Mnikley** [halirutan/IntelliJ-Key-Promoter-X#100]
**Describe the bug**
The displayed actions are shown in a dropdown and are only visible after clicking. This is caused by the 'New UI', which is still an experimental feature. However, Jetbrains support mentioned to contact the developer of the third party plugin first: [reference](https://youtrack.jetbrains.com/issue/PY-58015).

**To Reproduce**
Steps to reproduce the behaviour:
1. Set breakpoint by click
2. Check triggered Key Promoter X tooltip

**Expected behaviour**
Hotkey and further actions displayed directly in the tooltip.

**Screenshots**
Old UI (expected result):
![image](https://user-images.githubusercontent.com/75040444/208051064-8689fee0-531d-4fc9-a8b0-67cd65bbdcbe.png)

New UI:
![image](https://user-images.githubusercontent.com/75040444/208051106-ec9fd33d-cdc8-4e21-a578-0692410bc6af.png)

**Please also provide:**
 - OS: Windows 11 Version 22H2 (OS Build 22621.963)
 - IntelliJ Product: PyCharm 2022.1.3

**Comment by meszaroszoltan** [comment]
A lot of notifications are missing while using the new UI (IDEA 2022.03, MacOS Ventura).

**Comment by halirutan** [comment]
I did a session last night looking into that. On PyCharm 2022.3.1 I can see the whole notification, however I'm on Linux and not Windows

![image](https://user-images.githubusercontent.com/511683/211941320-7b21f4d2-5e2c-4b12-b899-ed454a957f3a.png)

Can someone please check if this was only a temporary regression in the IntelliJ Platform or if this is still an issue with newer versions?

The missing notifications that @meszaroszoltan mentions will be a lot of fun. To give an example: The new UI uses new rectangular buttons for the tool windows on the side. These are implemented in Kotlin as `internal` classes with no easy way to find out what Action was actually invoked. In the normal UI, the tool window buttons are `StripeButtons` and I could just do something like

```java
if (buttonWasPressed() && button instanceof StripeButton) {
    // do stuff to find out what toolwindow, actionID and shortcut this has
}
```

With the new UI, I can't even do

```java
if (button instanceof SquareStripeButton) {
    // ...
}
```

because the `internal` visibility doesn't let me do this. At the moment, I'm not sure how to solve this.

**Comment by Mnikley** [comment]
> I did a session last night looking into that. On PyCharm 2022.3.1 I can see the whole notification, however I'm on Linux and not Windows
> 
> ...
> 
> Can someone please check if this was only a temporary regression in the IntelliJ Platform or if this is still an issue with newer versions?
> 
The problem persists on Windows 11 Version 22H2 (OS Build 22621.1105) with PyCharm 2022.3.1 Build #PY-223.8214.51 (same as you mentioned):

![image](https://user-images.githubusercontent.com/75040444/212010023-9c2f19a1-0578-430e-b438-077862c2ca9e.png)

**Comment by halirutan** [comment]
@Mnikley I asked a colleague if this is a bug or intentional. Whether or not this information is hidden depends on the width of the text and the settings are different for Win, Mac and Linux. What we could try is that I provide a temporary Key Promoter version for you where I just shorten the text, and you check if this indeed solves the problem. 

If it does, then we could think about shortening the `"(Disable alert for this shortcut)"` text. It's ugly and I don't like it, but there seems to be no other solution when using the notifications of the IntelliJ Platform.

**Comment by Mnikley** [comment]
@halirutan sure, I can do some testing with temporary versions and shortened texts! Double clicking the tooltip does not open the Key Promoter tool window for me, or am i misunderstanding something? The 3 burger-dots in the top right corner open the generic IntelliJ notification options, but thats it.

**Comment by halirutan** [comment]
@Mnikley On the left border (usually), you have the Key Promoter tool window icon. If you open it, you see a summary of the shortcuts you missed and the ones you have silenced. You can double-click these entries to move them between "hitlist" and "suppressed list".

![image](https://user-images.githubusercontent.com/511683/212135481-708d999d-948e-486c-a270-8256e348084d.png)

**Comment by halirutan** [comment]
@Mnikley Could you please try out the following version? You must go to **File | Settings | Plugins** and press the small gear icon. There you select **Install Plugin from Disk...** and select the downloaded `.zip` file.

I reworked the display of the notifications and put all important information into the title and the message itself. So even when you don't see the actions, you still should see what shortcuts you missed.

[Key-Promoter-X-2022.3.1.zip](https://github.com/halirutan/IntelliJ-Key-Promoter-X/files/10407094/Key-Promoter-X-2022.3.1.zip)

**Comment by Mnikley** [comment]
@halirutan yeah, that works i guess. I think you could even get rid of the "Command: " part in the header to make it more compact. 
![image](https://user-images.githubusercontent.com/75040444/212263358-7f484bb6-e37e-49c9-a102-73b79daf7bb8.png)
