### ISSUE TITLE
Tool icon has low contrast in JetBrains Rider 2023.1 New UI

### ISSUE THREAD

**Issue by chrisyarbrough** [halirutan/IntelliJ-Key-Promoter-X#104]
Rider has [updated its UI](https://www.jetbrains.com/help/rider/New_UI.html#compact-mode) with a new design for plugins displayed in the sidebar:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/17833862/230798178-872e44ab-db0b-4b3a-a487-e738987de211.png">

**Issue:** When the Key Promoter X plugin tool window is displayed, the icon does not work well with the new blue highlight:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/17833862/230798218-d5781bb5-ce91-458b-8451-89d8adc9e3e5.png">
The icon has very low contrast and is hard to see on the blue background.

Other plugin icons have better contrast:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/17833862/230798263-d2f30e38-f187-4a33-8f2f-52ae4933c93f.png">

I don't know if the new UI supports/expects multiple icon variants for these different contexts or if it would be enough to make the Key Promoter icon brighter. Potentially JetBrains has some guidelines for plugin developers available.

**Affected Versions**
 - OS: macOS Ventura 13.3.1
 - JetBrains Rider 2023.1
 - New UI (beta), _Rider Night_ theme
 The issue may also affect other versions or systems.

The new UI and theme can be selected in the settings:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/17833862/230798574-543c3728-2cda-4ef2-afa3-30d0befd6aa3.png">

**Comment by halirutan** [comment]
Confirmed and debugged. It seems for the new UI, we need an icon mapping and it also requires very specific color-values in the SVG icons itself, so that they can be made brighter for the case when the toolwindow is active

![image](https://github.com/halirutan/IntelliJ-Key-Promoter-X/assets/511683/88542901-b5c2-45f6-9284-bfbe52949605)

And of course the massive X logo looks shitty now between all the slender outline logos. So that needs to be changed as well.

**Comment by halirutan** [comment]
That should work now, but if anyone knows an "open-source UI designer" with too much time, we should probably rework the tool window icons for the new UI because they are all _line style_ now 😜
