### ISSUE TITLE
Include mouse shortcuts as acceptable shortcuts

### ISSUE THREAD

**Issue by kajbaf** [halirutan/IntelliJ-Key-Promoter-X#106]
**Is your feature request related to a problem? Please describe.**
There are some tasks that are easier with a mouse shortcut than a keyboard shortcut. In such cases, i expect Key-Promoter to respect the mouse shortcuts and not complain about them.
For example:
- Cmd+Click to go to the declaration. While Cmd+B works great when you are on the variable, you can still use Cmd+Click when the cursor is not on the word and you want to go to the definition.
- I have set up Cmd+Ctrl+Right Click to copy the filename and Cmd+Shift+Right Click to copy the full path. It works great to go to Project view with Cmd+1, and then Cmd+Ctrl+Right Click on any file.

**Describe the solution you'd like**
If I am right-clicking on an object, or opening a menu and then selecting an option, I expect Key Promoter to force me to use the Keyboard shortcut. But if I have defined a Mouse shortcut, I expect Key Promoter to respect that as an acceptable shortcut.
Moreover, if there is only a Mouse shortcut for an action, I expect KeyPromoter to suggest that when I'm using menues.

**Describe alternatives you've considered**
One alternative is to turn off KeyPromoter for some actions. But that would be considered cheating.

**Comment by halirutan** [comment]
This is not possible due to technical limitations. Accessing the key map just shows me available shortcuts. I cannot find out if _you_ set the shortcut or if it is there by default. Even just finding shortcuts for actions is already a very hacky procedure since I need to work around many quirks.

Please see the KPX for what it is: A small tool to help you get started using the keyboard.
As soon as you're an advanced user, there's no need for it. You should know how to look up actions (and their shortcuts) with *Find Action* (`Ctrl`+`Shift`+`A` on Windows and Linux) or simply use *Find Action* to invoke anything that doesn't have a shortcut.
