### ISSUE TITLE
Plugin not warning for the click the not set the key

### ISSUE THREAD

**Issue by umitems** [halirutan/IntelliJ-Key-Promoter-X#11]
Plugin warning only click that already have its own key-map. However, I expected to warn any click that can have a key map. 

May be no need to warning for non-key just have an option to keep stat for other action? 
Or warning when non-key action when occur 10 times or more. This will suggest user to create their own key and gain more productivity.

**Comment by halirutan** [comment]
If I understand you correctly, then you mean Key Promoter shows suggestions for things that have only a "mouse short-cut". Unfortunately, this is not consistently possible. I get the available short-cuts from IDEA. I cannot filter them because they are plain text and sometimes a feature has a short-cut and a mouse action.
