### ISSUE TITLE
Non-dismissable nard mode

### ISSUE THREAD

**Issue by Andret2344** [halirutan/IntelliJ-Key-Promoter-X#114]
The modal with description of a shortcut can be closed. It'd be worth disabling it. To really force using the shortcut.

**Comment by halirutan** [comment]
I know of this _backdoor_ but hear me out. Let's say there is a way to make a dialog really un-closable with the mouse, and we force users to use the shortcut. Now, what happens if a user has the shortcut assigned to something else through the operating system? How will they be able to continue to work without re-assigning the OS shortcut?

The Key Promoter has roughly 100k downloads per month and I hope you can understand that this calls for trouble. So while your suggestion is perfectly fine, I'd like to keep the "safe hard mode".
