### ISSUE TITLE
Support 2024.1 EAP

### ISSUE THREAD

**Issue by rakleed** [halirutan/IntelliJ-Key-Promoter-X#118]
Can you please add support for version 2024.1 EAP?

**Comment by CrazyBoy49z** [comment]
Upd: Support 2024.1 RC

**Comment by CrazyBoy49z** [comment]
Upd: Support 2024.1

**Comment by halirutan** [comment]
I updated everything to IntelliJ Gradle Plugin 2.x, but currently the Key Promoter X release is blocked by this issue

https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1255

If I can't work out a solution with Jakub within the next few days, I'll publish the new KPX version using the old Gradle version. But I really wanted to make this transition with the new release. Sorry for the delay.

**Comment by Kroppeb** [comment]
Oof, that sucks. I hope it gets fixed soon, because this is a very useful plugin.

**Comment by halirutan** [comment]
I published the new version 2024.1 and used the old Gradle plugin 1.x for now.

As for Gradle plugin 2.x, the instrumentation issue wasn't bad at all. Only the error message was highly confusing. So building Key Promoter X with Gradle plugin 2.x does work now. However, the GitHub actions for automatically building and publishing Key Promoter X need to be reworked since Gradle tasks changed. I try to get it working in the next Key Promoter X version.
