### ISSUE TITLE
Ctrl+left click is suggested but not recognized

### ISSUE THREAD

**Issue by leveluptor** [halirutan/IntelliJ-Key-Promoter-X#14]
When I go to declaration using Ctrl+left click, there is a popup which suggests using "Ctrl+B" or "Ctrl+Button1 Click", which seems to be what I'm doing anyway.

I noticed https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/11 but not sure if this is the same thing.

![key-promoter-ctrl-click](https://user-images.githubusercontent.com/18212170/35149121-0294b3c6-fd26-11e7-8d54-5fb67908b464.gif)

IDEA version 2017.3.2, plugin version 5.11.

**Comment by halirutan** [comment]
IDEA sometimes has more than one short-cut for a particular action. I'm always displaying *all* short-cuts and since they are simple strings, I'm just presenting them without filtering out what you actually did. Maybe, when I have too much free time, I'm considering removing the mouse action you invoked from that list.

Currently, you'll have to live with this. You used a mouse action that has a short-cut so you're seeing all short-cuts. There are only a handful (if it is even a handful) of such actions and *Go to declaration* is one of them.

Nevertheless, thanks for sharing the issue.

**Comment by leveluptor** [comment]
Thanks for the explanation! This is a very minor issue for me, just wanted to know if it works as expected.

**Comment by tlinkowski** [comment]
I also stumbled upon this issue.

I started removing other shortcuts, and I found out that the balloon is presented even if "Ctrl+Button1 Click" is the **only** shortcut. So it seems the plugin indeed does not recognize those mouse-related shortcuts. Is it expected (the plugin being a *key* promoter) or is it a bug?

Moreover, after reducing the number of shortucts, I found out there's actually a `(Don't show again)` link, which gets hidden if there are too many shortcuts (see the [GIF](https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/14#issue-289949364) posted by @leveluptor  - you can only see the initial `(D` of this link there). I clicked this and it solved this problem for me but maybe this `(Don't show again)` should be moved to the next line?

**Comment by halirutan** [comment]
> I clicked this and it solved this problem for me but maybe this (Don't show again) should be moved to the next line?

@tlinkowski That is a good idea.

Since most of the issues reported are about the mouse-shortcuts that appear in KPX, I will do some further digging if I can handle them more appropriately.

**Comment by jbeckers** [comment]
Seeing the same thing with "back" aka "ctrl+alt+left" aka "button4 click".

I would argue that "Maybe, when I have too much free time, I'm considering removing the mouse action you invoked from that list." is not a great solution.
I'd say Key Promoter should not show a message at all, in this case.

In other words: if any of the short cuts for the action is in the list, no need to promote the others.

**Comment by mazabin** [comment]
I created shortcut for action with no default shortcut - double click with a mouse wheel, but it's not recognized either.

> I'm always displaying all short-cuts and since they are simple strings, I'm just presenting them without filtering out what you actually did.
This is not actually true. 
Go to Declaration has by default few shortcuts: ctrl+b, ctrl+ left mouse button click.
Ctrl+B doesn't show the balloon, whereas ctrl+click does.

So in what I observed, no mouse-related shortcuts are recognized.

**Comment by halirutan** [comment]
@mazabin I read your message several times, but I'm confused. Let's start from the beginning:

> double click with a mouse wheel, but it's not recognized either.

Have you in the latest release of KPX version 2019.1.1 turned **off** "Show Keyboard Shortcuts Only"? It's under Settings | Tools | Key Promoter X.

If I do this and create a shortcut for  "Move Caret Backward a Paragraph" setting it to `Ctrl`+`Alt`+`Shift`+`Mouse 2`, I get

![img](http://i.imgur.com/th1KtHK.png)

> This is not actually true.
> Go to Declaration has by default few shortcuts: ctrl+b, ctrl+ left mouse button click.
> **Ctrl+B doesn't show the balloon, whereas ctrl+click does.**

It is a feature that nothing is displayed when you press `Ctrl`+`B` because the whole purpose of KPX is to show you shortcuts for mouse-actions. Once you know the short-cuts and actually use the keyboard, there is no use in displaying them again. Can you explain what you mean here?

> So in what I observed, no mouse-related shortcuts are recognized.

I specifically introduced the new setting I mentioned above since there seems to be a general disagreement between users what to show and what not. You can see it directly in this issue. The OP of the issue complained that he doesn't want to see a notification for the mouse shortcut he is actually using. You on the other hand complain that you don't see a notification for you mouse action. https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/18 and https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/10 go into the same direction.

Therefore, I implemented the "Show Keyboard Shortcuts Only" which filters the list of shortcuts and selects only keyboard shortcuts. With this setting turned on, you will get

![img](http://i.imgur.com/YGwZ2oS.png)

which doesn't show the `Ctrl`+`Click` shortcut. If the list of shortcuts is empty after removing all mouse actions, then nothing is displayed like in your case with the double-click. With the setting off, you will see

![img](http://i.imgur.com/D4AbCEZ.png)

which includes the mouse shortcut.
