### ISSUE TITLE
Optionally prevent action if shortcut exists

### ISSUE THREAD

**Issue by nicolaiparlog** [halirutan/IntelliJ-Key-Promoter-X#26]
IIRC the original Key Promoter plugin had a setting to prevent an action for which a shortcut existed. That rather extreme setting helped me a lot in starting to use settings. Could it be implemented in Key Promoter X?

**Comment by halirutan** [comment]
Yes, I understand and it indeed seems like an extreme, but funny way to force users to keep their hands off their mouse. Unfortunately (better, "fortunately"), the *new* Key Promoter uses the InteliJ API to listen to mouse actions through the `com.intellij.openapi.actionSystem.ex.AnActionListener` instead of capturing raw AWT events.

However, with this listener, it seems not possible to prevent the action from happening. Additionally, Key Promoter X uses a combination of this action listener and a raw `AWTEventListener` since some buttons (the tool-window stripe buttons around the IDE) are not reported. This further complicates things.

So, until I find a reasonable way to implement this, I cannot even think about if it is a good idea to provide this features. I'll leave this issue open for now. Maybe I'll come back to it in the future.
