### ISSUE TITLE
Capture run configuration drop-down

### ISSUE THREAD

**Issue by reitzig** [halirutan/IntelliJ-Key-Promoter-X#28]
The configuration dropdown:

![image](https://user-images.githubusercontent.com/4246780/47497774-7452b100-d85b-11e8-98ea-cf52931e36be.png)

Can also be opened with Alt+Shift+F10:

![image](https://user-images.githubusercontent.com/4246780/47497808-90eee900-d85b-11e8-98e3-26e559121f23.png)

Well, I guess it's a slight variation, but it can do all the drop-down can.

Please make the plugin tell us about this shortcut whenever we click the drop-down.

**Comment by reitzig** [comment]
Arguably, the same shortcut should be proposed when we click a "Run" gutter icon.

**Comment by halirutan** [comment]
I have to check, why these buttons are not captured by `AnActionListener`.

**Comment by halirutan** [comment]
Unfortunately, these things appear to be handled entirely by the UI and don't fire an action. Therefore, I don't get notified in the KPX code.

**Comment by reitzig** [comment]
Do you think it would make sense to create a ticket on the IDEA Youtrack?

**Comment by halirutan** [comment]
@reitzig With my current understanding, I'd argue that it doesn't make sense to create a ticket because this is impossible to fix. Let me explain why I believe this: Assume you have a simple GUI with a button and a tooltip for the button. When you go over the button, the tooltip is shown but when you click on the button, the GUI actually invokes a more complex activity that needs to set-up data, etc. before the GUI can let's say display something.

In the Key Promoter, we rely on that there is a real activity behind the button that is pressed because this activity (called `AnAction`) *often* sends a message that it ran which I can capture with `AnActionListener`. Things like tooltips or in this case opening the dropdown for Run Configs don't invoke any action. They are entirely handled by the UI and the action-system will only capture when you actually press on a button to do something real.

This is why I believe this cannot be fixed. The action of opening the drop-down menu is not recorded because it never reaches the action system. And that there is a short-cut for it doesn't mean anything.
