### ISSUE TITLE
Settings: "Clicks before notifications is shown" can not be set to 10 or higher

### ISSUE THREAD

**Issue by fschoenm** [halirutan/IntelliJ-Key-Promoter-X#30]
The settings of how many clicks are needed before a notification is shown can only be set to a value of 1 to 9. What about higher settings? I don't think a maximum number of 9 is very reasonable.

(Linux, CLion v2018.3.3, Key Promoter X v5.12)

**Comment by halirutan** [comment]
Hehe.. yep, you are correct. I set the maximum to 9 and for me, this is also not a reasonable setting. I would have kept it at "show the thing every time" :smile:

Jokes aside, I can raise the limit in the next release, but there is a reason behind it. I think of the KPX as a short time tool of 1-6 months. It should be as annoying as possible and force you to learn the shortcuts you really need. For the things you *want* to do with the mouse, you can turn the notification off. For everything else, KPX should help you to learn the shortcuts as fast as possible. That means showing the notification every time.

After you are up to speed, you can remove the plugin because then, you have learned all the most important things and you know that you can quickly lookup every action with `Ctrl` + `Shift` + `A`.

I'll keep this issue open and increase the limit for the next release.

**Comment by halirutan** [comment]
Set limit for both values to 30. Fixed in next release.

**Comment by fuzzyweapon** [comment]
Sometimes habits slip, or we tweak key bindings.  It's nice to have more control to top out or find different usages for us (even if I find value in your perspective @halirutan).  Thank you!  As someone who has chronic ADHD, sometimes I like to fluctuate this value based on how I feel I've been performing with my keyboard shortcuts lately (to keep myself in shape XD).  For some reason I still have a lot of mousing instincts.  So for me, I've kept this plugin on for years, bc it helps keep my memory in shape without having to do more disruptive actions like activating/deactivating the plugin more frequently than convenient.  It also allows me to slowly increase my keyboard usage to more shortcuts over time while still being productive, try out new keybindings and monitor how useful they are to me beyond feel (I will go the mouse if I feel a key binding is inconvenient so it's good for discovering some key bindings that need adjusting).  Ty!

**Comment by fuzzyweapon** [comment]
In fact, I wish I had this plugin implemented as a desktop wide thing.  It's really awesome. 😄

**Comment by halirutan** [comment]
@fuzzyweapon 

>  For some reason I still have a lot of mousing instincts.

I have different modes of operation as well. When I write code, I don't use the mouse much and I have muscle-memory for most things like navigation, VCS, refactoring, building, running, etc..
However, when I debug IntelliJ plugins, it's really useless to *not* use the mouse. In that case, clicking between the IntelliJ sandbox and the debugging IDEA is faster.
