### ISSUE TITLE
Make plugin compatible with IDE version 2019.1

### ISSUE THREAD

**Issue by prigara** [halirutan/IntelliJ-Key-Promoter-X#31]
The Early Preview for 2019.1 has started and it would be awesome to have a plugin compatible with this version.
Thanks!

**Comment by halirutan** [comment]
@prigara To explain why it wasn't updated: My original plan was to make some fixes, create new icons which follow the [IntelliJ Platform UI Guide](https://jetbrains.github.io/ui/) and publish the plugin through the JetBrains Marketplace.

Since rolling out the marketplace takes way longer than anticipated in August 2018, I decided to push the new version now.

**Comment by roman-vi** [comment]
Hello @halirutan, what about current plans for 2019.1 compatibility?

**Comment by halirutan** [comment]
@roman-vi What exactly are you referring to? I have published a version that should be compatible with 2019.1 at the end of January. Is anything wrong or doesn't work? See here the latest version:

https://plugins.jetbrains.com/plugin/9792-key-promoter-x

**Comment by roman-vi** [comment]
Thanks for instant reply! I just didn't find it and my older version didn't update automatically so I misunderstand current state. Now it works.
