### ISSUE TITLE
Capture tab clicks

### ISSUE THREAD

**Issue by bric3** [halirutan/IntelliJ-Key-Promoter-X#33]
When selecting a tab with the mouse like Editor tabs, terminal tabs, vcs tool tabs, etc.

Suggest the related shortcuts 
![terminal-tabs](https://user-images.githubusercontent.com/803621/52703952-cbea6900-2f7f-11e9-9039-ecc86da1d69b.png)

 - Main menu > Window > Editor tabs > Select Next Tab (Activate next tab) : 
    - <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>[</kbd> 
    - <kbd>⌃</kbd> + <kbd>←</kbd> 
 - Main menu > Window > Editor tabs > Select Next Tab (Activate next tab) : 
    - <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>]</kbd>
    - <kbd>⌃</kbd> + <kbd>→</kbd> 

When on a tab menu
![vcs-tabs](https://user-images.githubusercontent.com/803621/52703751-5c747980-2f7f-11e9-9881-af4625cac694.png)

 - Main menu > Window > Active tool window > Show list of tabs : 
   - <kbd>⌃</kbd> + <kbd>↓</kbd>
   - <kbd>⌃</kbd> + <kbd>⌘</kbd> + <kbd>↓</kbd>

![keymap](https://user-images.githubusercontent.com/803621/52703658-246d3680-2f7f-11e9-8523-0fb3f1f2f41c.png)

**Comment by bric3** [comment]
One can even think about showing the shortcut of `Rename session` for the terminal tool window.

**Comment by halirutan** [comment]
The trouble is that I'm relying on getting notified when a click-action fired. There are two ways for this: The most reliable is when I get notified through `com.intellij.openapi.actionSystem.ex.AnActionListener` because then, chances are very good that I will get the `ActionID` and I can access the shortcut.

The fallback method is to catch the raw `AWTEvent` which I only do for some rare cases like the Toolwindows. The problem is that the `AWTEvent` has nothing to do with IntelliJ internal action system and I need check, e.g. which object received the button click. For the Toolwindows, for instance, this is always a `com.intellij.openapi.wm.impl.StripeButton`. This is highly fragile when used in general and I don't want to break other parts of the plugin.

In your case, the object that receives the click is an instance of `com.intellij.openapi.wm.impl.content.ContentTabLabel`. I'm sure you see that chances are very good a `ContentTabLabel` is used in many other places the shortcut might not be available. This will probably result in more wrong behaviour than we want to see.

To make it short: I can show KPX notifications for all buttons that are captured by IntelliJ `AnActionListener`. Only in a few exceptions, it is possible to inspect the raw `AWTEvent` and make good predictions on what button exactly was pressed and which shortcut it has.

**Comment by bric3** [comment]
Hi @halirutan Thank you very much for your explanation. Indeed that something that could be improved IntelliJ side.
