### ISSUE TITLE
Can I buy you a coffee?

### ISSUE THREAD

**Issue by Bored0ne** [halirutan/IntelliJ-Key-Promoter-X#38]
I just want to say thanks for the hard work! I love this plugin!
https://www.buymeacoffee.com/ ?

**Comment by halirutan** [comment]
Unfortunately, I'm not a coffee drinker (and it would be yet another site I have to register) :smile:
I have a Paypal option for donations, although I realise that this is probably one of the worst choices. From a $1 coffee, Paypal drinks about 37% before I get the cold leftovers.

I admit I haven't put too much thought into this when I linked to my Paypal account. Probably something like Patreon would have been better, but it seems that fits more for people who constantly make videos and music. It would be nice to have a "fan base" where it is *not* required to donate something.

So you don't have to bother with the coffee. Simply enjoying the Keypromoter is enough and maybe giving the repository a star. I'm anyway the more the Moster Energy type of person and since you come from Texas, I'm very sure it wouldn't be ice-cold any more when it reaches Germany :)

Have fun.

**Comment by Bored0ne** [comment]
That's fair I definitely starred it. Thanks for all the hard work!
