### ISSUE TITLE
Showing short cuts which i haven't configured

### ISSUE THREAD

**Issue by chamisf** [halirutan/IntelliJ-Key-Promoter-X#4]
Key promoter shows some suggestions that i have no mapping shortcut. For an example it suggest me to use 'Alt + N' for annotate a class or hide opened view with 'Shift + Esc' which is not working because those not configured yet. Is this the desired behavior? Or is it a suggestion for me to configure and use. I've default key mapping btw.

PS: Thank you for the awesome plugin.

**Comment by chamisf** [comment]
Seems it is not the case keys are configured but not working. Shouldn't be a problem with plugin.

**Comment by halirutan** [comment]
I need to clear this particular part up in the README: The main problem is that you can access different *contexts* with your mouse simply by clicking in it and that some shortcuts are only defined in this context.

Let me give a specific example: Inside the editor, press `Alt+1` to open and activate the "Project View" tool-window. *Now* press `Shift+Esc` and you see that the shortcut for closing that active tool-window works. The problem is that when you click on it with the mouse, I only see which action you have invoked but I cannot get the circumstances (here, that the tool-window needs to be active to make the short-cut work).

To conclude, you cannot always take the suggestion for granted and assume they work everywhere. Many do, but others only work in a specific context. What you should do then is use the suggestion as an indicator that there is a shortcut for it.
