### ISSUE TITLE
config display time and font size in setup

### ISSUE THREAD

**Issue by yxd0018** [halirutan/IntelliJ-Key-Promoter-X#48]
Is there a way to set display time and font size in setup?

**Comment by halirutan** [comment]
I did a quick check if the default Notifications let you adjust the time out, but nothing sprang into my eyes. I'm sure the font is taken from the default IDE settings and cannot be changed for every notification group.

We use the standard notifications that the IntelliJ API provides because we want the KPX to work consistently on as many IntelliJ products as possible. The old 2012 Key Promoter had exactly this problem: the UI slowly broke down when the IntelliJ API changed and/or new Java versions were introduced.

For the official release, I'd like to stick to normal notifications, but if you like to adjust this for you, take a look at the [Key Promoter Notifications class](https://github.com/halirutan/IntelliJ-Key-Promoter-X/blob/master/src/de/halirutan/keypromoterx/KeyPromoterNotification.java)?
