### ISSUE TITLE
layout for horizontal tool windows

### ISSUE THREAD

**Issue by keturn** [halirutan/IntelliJ-Key-Promoter-X#55]
I tried moving Key Promoter from its place on the right-hand side to one of the slots on the bottom. Its box layout doesn't handle it well.

![Screenshot showing text areas showing less than a line of text.](https://user-images.githubusercontent.com/83819/82735079-f0310b80-9cd3-11ea-9e62-919343cafb5d.png)

Looks like, at the minimum, it wants a scrollable container.

I'd also consider allowing the missed-shortcuts and suppress-tips list areas to be side by side.

I don't know how Swing does layouts or what its options for responsive layouts are, but in CSS terms I'd try out flexbox.

(Probably in normal usage people don't have this open much? but the notifications aren't showing, so I went looking. That's a different issue, though.)

**Comment by halirutan** [comment]
I never tried this to be honest.

> Looks like, at the minimum, it wants a scrollable container.

I fixed that but one cannot really use the mouse-wheel since the missed- and suppressed-list are catching the event. But it works.

> I don't know how Swing does layouts or what its options for responsive layouts are, but in CSS terms I'd try out flexbox.

That's, unfortunately, a different story. The panel uses IntelliJ's UI designer and has a `GridLayoutManager`. I'm sure one could directly implement this small panel directly in code and make it reflow, but it's definitely not what you'd know from "responsive  web apps".

> Probably in normal usage people don't have this open much? but the notifications aren't showing, so I went looking. That's a different issue, though.

Are you sure you have not turned off the notification balloons for the Key Promoter? This issue has popped up a few times. Can you look at [this comment of mine](https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/13#issuecomment-354263977)?

**Comment by keturn** [comment]
that last seems to have resolved itself after I filed this issue. Maybe it just wanted me to pay some attention to it first?

**Comment by halirutan** [comment]
You can try this release by manually installing it in the **Settings | Plugins** section

https://github.com/halirutan/IntelliJ-Key-Promoter-X/releases/tag/v2020.1.3.4

**Comment by halirutan** [comment]
OK, the scrollbar quickfix is published now.
