### ISSUE TITLE
Count number of shortcut used

### ISSUE THREAD

**Issue by davidsommer** [halirutan/IntelliJ-Key-Promoter-X#61]
It would be fun and encouraging to see how many times i used a shortcut next to how many times i clicked it.

**Comment by halirutan** [comment]
Hacky since I didn't plan for that but it seems possible. Here is a first prototype

![image](https://user-images.githubusercontent.com/511683/90994123-f88d3100-e5b7-11ea-8f34-0f3bb75a3200.png)

Would that be what you imagined? Any suggestions for the presentation i.e. is "12x missed, 3x recalled" understandable or do you have a better suggestion?

**Comment by davidsommer** [comment]
@halirutan looks goot, maybe recalled isn't the perfect wording but i'm not getting a better idea right now :-) Maybe missed / used  or missed / applyed.

**Comment by halirutan** [comment]
I guess "missed, used" is the better alternative. Each line shows a *shortcut* and you can either "miss" it or "use" it. That sounds not too far fetched.
