### ISSUE TITLE
Buttons in "Find in Path" do not trigger Key Promoter X

### ISSUE THREAD

**Issue by oscar-broman** [halirutan/IntelliJ-Key-Promoter-X#62]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Open "Find in Path"
2. Click on one of the buttons to the right: **Aa**, **W**, or **.***

**Expected behaviour**
A notification should inform me that I could use a shortcut instead (for example, Ctrl+Opt+X to toggle regex)

**Please also provide:**
IntelliJ 2020.1.2 with Key Promoter X 2020.2

**Comment by halirutan** [comment]
Unfortunately, there is no reasonable way to fix this, and the unreasonable way is neither future-proof nor maintainable. It often happens with actions that are part of a dialogue and only apply in specific contexts. What's usually done is that these actions are locally defined and stay local, which means they are not communicated by the `AnActionListener`.

In your specific case, the regex toggle button [is defined here](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/find/impl/FindPopupPanel.java#L621-L626). These are not global short-cuts and to the best of my knowledge, you won't find them in the **Settings | Keymap** listing because they wouldn't make sense there since they're only valid in the specific case when the find dialogue is open.

To catch these things, one had to grab the raw AWT event and inspect the class. This means I need to brute-force my way into the private variables of this class to extract the action that was used. I'd need to do this for each possible IntelliJ dialogue and each situation would require a different approach. The only situation I'm doing this is for the tool-window buttons because they are quite important.

Sorry for the bad news, but that's not something that is maintainable through all IntelliJ IDE's and for a longer time without much effort.
