### ISSUE TITLE
Mouse click shortcuts will prompt "Want to create a shortcut?"

### ISSUE THREAD

**Issue by patrickkusebauch** [halirutan/IntelliJ-Key-Promoter-X#76]
**Describe the bug**
I have "Apply Kubernetes file to context" bound to mouse button 4 (side button). This plugins still tries to convince me to assign a shortcut instead. But this is the shortcut.

**Please also provide:**
 - OS: Ubuntu
 - IntelliJ Product: PHPStorm

**Comment by halirutan** [comment]
Does this happen even when you have checked "Show only Keyboard Shortcuts"?

![image](https://user-images.githubusercontent.com/511683/110260886-4b579480-7fae-11eb-82dc-a16dfe472124.png)

**Comment by patrickkusebauch** [comment]
@halirutan Yes, Yes it does.

**Comment by halirutan** [comment]
OK, I guess I misunderstood the situation. So when you press your mouse-button 4, you don't see a notification like this

![image](https://user-images.githubusercontent.com/511683/111114662-cf3bee80-8563-11eb-9014-f3f563e565cf.png)

Instead, you see a notification similar to this

![image](https://user-images.githubusercontent.com/511683/111114715-ebd82680-8563-11eb-92c5-c84afd66facd.png)

Right?

**Comment by patrickkusebauch** [comment]
@halirutan Neither, I see this:
![Screenshot from 2021-03-15 08-00-39](https://user-images.githubusercontent.com/1620948/111115231-9b14fd80-8564-11eb-90ce-ddcccdf88265.png)

**Comment by halirutan** [comment]
Yep, so it is the "Want to create a shortcut ..." notification.
This is a very unfortunate situation that sadly can't be fixed easily because you have assigned a "shortcut" that is really a mouse click :)

When you expand this message, you should see a "(Disable alert for this shortcut)" message. Have you tried this?

**Comment by patrickkusebauch** [comment]
@halirutan no. And I am sure this would "resolve the issue". I don't mind it, this is more of a "just letting you know, in case you don't know already" type of situation.

**Comment by halirutan** [comment]
Yes, and it's a good thing that you did because I see now that there is an underlying issue. I was just able to reproduce it and understand what's wrong:

1. When you have turned on the Key Promoter X setting "Show only keyboard shortcuts" that it won't give you a "you missed XX" message for shortcuts that only have Mouse shortcuts. For me, this was the middle-click which is "Paste from X Clipboard".
2. Everything works fine which means when I use the middle-click, then I get no message from Key Promoter
3. However, the KPX will still ask me if I want to create a shortcut for it which I haven't noticed before

Therefore, I missed implementing the "only show keyboard shortcuts" check for the "do you want to create a shortcut" notifications.

**Comment by halirutan** [comment]
I _believe_ I fixed the issue.
