### ISSUE TITLE
Duplicate items in the hitlist

### ISSUE THREAD

**Issue by packagewjx** [halirutan/IntelliJ-Key-Promoter-X#8]
First of all, this plugin is great, and thanks for your hard work.
But there is a small problem. In the missed short cut hitlist, there are some items, I think they are duplicates. For example, 'Shift + F10' appears many time, with different application I run. It's like *'Shift + F10' for Run '...' (pressed 45 times)*, and *'Shift + F10' for Run '...(another application)' (pressed 36 times)*.
![image](https://user-images.githubusercontent.com/18662061/30364174-aaef8028-9895-11e7-97ff-00c0dd47f0e7.png)
Some hot key advices are based on current editing files or current context, although they are suggesting the same hot key, like 'Shift + F10', 'Ctrl + F5', 'Ctrl + F2', and so on. I think **they can be calculated in one item in the list**.
Happy coding,
packagewjx

**Comment by halirutan** [comment]
Yes, you are correct. Still, I'm not able to fix this in a meaningful way. There are several IDEA actions that have the same short-cut in different contexts. In your case, the situation is clear: Press `Shift+F10` for `Run`. Other cases might have completely different *descriptions of the action* and I get the descriptions from the IDEA action itself, so I don't have any influence on that. I don't see a consistent way of creating a meaningful general description when two actions have the same shortcut but different action texts.

Even if this would be possible, chances are good that I merge two actions and users are puzzled by the description because it doesn't say exactly what they tried to do.

**Comment by G-Rath** [comment]
@halirutan would you be open to making this an opt-in option for users?

I really love this plugin, and while it's a pain in the ass, I know that the fact it's so annoying at times is why it's so great; however in this situation it is just plain annoying - in my case, it's actually a matter of I don't really want to use `Shift+F10` b/c I think it's not the smoothest of key commands.

I'd gladly give up being told about any possible things I could do w/ `Shift+F10`, if it meant that I'd not be told about *every single variation of run*.

Would pattern matching be viable at all? I suspect that'll fall over w/ translations, but I can't think of any actions that would match `"Debug '.*?''`, `"Run '.*?'"`, etc

Then that way you could use the regex as the descriptor.
