### ISSUE TITLE
The plugin is causing GoLand to freeze after resume

### ISSUE THREAD

**Issue by lzap** [halirutan/IntelliJ-Key-Promoter-X#98]
Hey, I am not sure what is going on, but I have a pretty clean GoLand installation and I've decided to give your plugin a try, looks awesome. But when my system (Mac Mini M1 16GB) goes sleep and I wake it up, the whole IDE is stuck, the main window does not refresh. I can still do actions like menu, preferences, quit the app. Nothing in the logs at all, it thinks it is operating normally.

Only after I disable the plugin, it works again. I am on MacOS Ventura.

I am uninstalling for now, thought I would drop you a bugreport just for the record someone else is hitting this. Cheers!

**Comment by lzap** [comment]
Okay I just experienced the issue with your plugin uninstalled. I guess something is wrong with my setup :-( Sorry for the noise.

**Comment by halirutan** [comment]
Hey @lzap. Wanted to reply this weekend, but my assessment would have been the same. The Key Promoter X doesn't do weird or complicated things and I would have asked you if you really excluded any other reasons why your GoLand is broken.

On a side note: Go to the Help menu and click on "Show Log in Finder" so that you know where the log file is. Close GoLand and delete the current log file. Open it up again and when you experience the refresh error, look if you can find anything suspicious there like exceptions, etc.

However, it's also possible that this bug comes from a weird operating system interaction and you won't find anything there. Good luck.

**Comment by lzap** [comment]
Thanks it was a known bug in IntelliJ, confirmed, they are pushing a fix soon. Sorry for the noise. Not sure why I assigned you, that was a mis-click. Cheers!
